### PR TITLE
setup react application

### PR DESCRIPTION
**Pull request by petushka1**
### Setup app

- [x] setup repository 
- [x] sutup github workflows 
- [x] install linter packages 
- [x] add react to the project

### CODE REVIEW

**Review by FrederickMih — COMMENTED** [review]
Hi @petushka1 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**You have submitted a project, that does not contain a descriptive README file. Also, GitHub action is not enabled(Kindly check your Linters configurations)**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by petushka1** [comment]
Oh, sorry. Can you advise, please? I followed the link to submission on the dashboard.
image

**Comment by FrederickMih** [comment]
@petushka1, you'll need to click on **Actions**, then **submit**. Fill in the form including the link to your PR. 

Hope that help!.

**Review by TedLivist — CHANGES_REQUESTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @petushka1,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### 1. You have submitted a project that does not have a descriptive README. Kindly format your README using the [Microverse template](https://github.com/microverseinc/readme-template) and add all required sections

  petuska-1

### 2. You are yet to set up your linters. Visit [this link](https://github.com/microverseinc/linters-config/tree/master/react-redux) to set your linters. From the image below you also need to move the files in the highlighted `my-app` folder to the root directory

  petuska-2


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Davidosky007 — APPROVED** [review]
Hi @petushka1 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## [OPTIONAL]

* I strongly suggest you rearrange your file structure as all your files should be in just one folder not nested ( eg all files should be in the math-magicians-app folder ) or you update your readme file on setup instructions on how to properly install your app ( ie after cloning the app cd into `math-magicians-app` and then cd into `my-app` before runing `npm i`
image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
